apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/cert-manager  # Points to dir with raw YAMLs
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/certificates
  prune: true
  dependsOn:
    - name: infrastructure