apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.11.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    installCRDs: true  # Critical!