# cluster/cert-manager/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster/cert-manager
  prune: true

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/certificates
  prune: true
  dependsOn:  # Ensures cert-manager is installed first
    - name: cert-manager